name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {python: '3.10', tox: py310}
          - {python: '3.9', tox: py39}
          - {python: '3.8', tox: py38}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install -U wheel
        pip install -U setuptools
        python -m pip install -U pip
    - name: Install tox
      run: pip install tox
    - name: Run tox
      run: tox -e ${{ matrix.tox }}
